services:
  - type: web
    name: current-affairs-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: current-affairs-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: current-affairs-db
    databaseName: current_affairs
    user: current_affairs_user